version: "{branch}-ci-{build}"
image: Visual Studio 2022

build: msvc
platform: x64
configuration: Release

build_script:
 - git submodule update --init --recursive
 - mkdir build
 - cd build
 - cmake ..
 - cd ..
 - cmake --build .\build\ --config Release
 - .\build\Release\SimpleHashTest.exe --confidence=50 --filter=CtorDtor* --output=csv/test01.csv
 - .\build\Release\SimpleHashTest.exe --confidence=50 --filter=ClearAndInsertSeq* --output=csv/test02.csv
 - .\build\Release\SimpleHashTest.exe --confidence=50 --filter=InsertRndClearAndReInsert* --output=csv/test03.csv
 - .\build\Release\SimpleHashTest.exe --confidence=50 --filter=InsertRndAndRemove* --output=csv/test04.csv
 - .\build\Release\SimpleHashTest.exe --confidence=50 --filter=CtorSingleEmplaceDtor* --output=csv/test05.csv
 - .\build\Release\SimpleHashTest.exe --confidence=50 --filter=InsertAccessWithProbability10* --output=csv/test06.csv
 - .\build\Release\SimpleHashTest.exe --confidence=50 --filter=InsertAccessWithProbability50* --output=csv/test07.csv
 - .\build\Release\SimpleHashTest.exe --confidence=50 --filter=SearchNonExisting* --output=csv/test08.csv
 - .\build\Release\SimpleHashTest.exe --confidence=50 --filter=SearchExisting* --output=csv/test09.csv

after_build:
- cd csv
- "python combine.py > combined.csv"
- cd ..
- 7z a results.zip %APPVEYOR_BUILD_FOLDER%\csv\*.csv

artifacts:
- path: results.zip
  name: Test Results


